# Generated by Django 3.2.5 on 2021-07-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='toko/thumbnail')),
                ('nama_toko', models.CharField(max_length=255, verbose_name='Judul')),
                ('alamat', models.TextField(blank=True, null=True)),
                ('telp', models.CharField(blank=True, max_length=15, null=True)),
                ('frame_maps', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
