# Generated by Django 3.2.5 on 2021-07-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sejarah'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='berita/thumbnail')),
                ('judul', models.CharField(max_length=255, unique=True, verbose_name='Judul')),
                ('isi', models.TextField()),
                ('penulis', models.CharField(blank=True, max_length=255, unique=True)),
                ('durasi', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
