# Generated by Django 3.2.5 on 2021-07-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_berita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='penulis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='berita',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='core/static/berita/thumbnail'),
        ),
    ]
